// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccX1H7TtvjW96wxyayjaiNOJ2t4HtVBY',
    appId: '1:1071845763488:web:d29432027eece36f29dcc5',
    messagingSenderId: '1071845763488',
    projectId: 'rob-midterm',
    authDomain: 'rob-midterm.firebaseapp.com',
    storageBucket: 'rob-midterm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMpLpgLzTDAzKaW2_YK5SRWp2IVbowxuk',
    appId: '1:1071845763488:android:ccffd544c7f1899e29dcc5',
    messagingSenderId: '1071845763488',
    projectId: 'rob-midterm',
    storageBucket: 'rob-midterm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz2Uiv_6NBWpwpSgz6TygWFMpDA_CMoCI',
    appId: '1:1071845763488:ios:1362068eaec527d229dcc5',
    messagingSenderId: '1071845763488',
    projectId: 'rob-midterm',
    storageBucket: 'rob-midterm.appspot.com',
    iosClientId: '1071845763488-f4u9no4galcme0hb15ngsnh7vs72npnv.apps.googleusercontent.com',
    iosBundleId: 'com.mdsdc.midterm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz2Uiv_6NBWpwpSgz6TygWFMpDA_CMoCI',
    appId: '1:1071845763488:ios:1362068eaec527d229dcc5',
    messagingSenderId: '1071845763488',
    projectId: 'rob-midterm',
    storageBucket: 'rob-midterm.appspot.com',
    iosClientId: '1071845763488-f4u9no4galcme0hb15ngsnh7vs72npnv.apps.googleusercontent.com',
    iosBundleId: 'com.mdsdc.midterm',
  );
}
